import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';
import { Toaster } from 'react-hot-toast';
import './globals.scss';

export const metadata: Metadata = {
  title: 'LeetCode clone',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
